library(usethis)
library(devtools)
library(progress)
## data reformat
library(pbapply)
library(data.table)
library(dplyr)
library(MSnbase)
library(igraph)
## visualize
library(ggplot2)
library(ggraph)
library(ggsci)
library(stringr)
library(grid)
## suggest
library(ChemmineR)
library(ChemmineOB)
library(rsvg)
library(grImport2)
library(ggimage)
load_all("~/MCnebula/R")
usethis::create_package("MCnebula")
load_all()
check()
use_mit_license("Lichuang Huang")
use_package("data.table", type="Imports")
use_package("dplyr", type="Imports")
use_package("progress", type="Imports")
